version: '3.8'
services:
  usersvc:
    build: .
    command: [ "hypercorn", "src.user:app", "--bind", "0.0.0.0:5050" ]
    ports:
      - "5050:5050"
    volumes:
      - ./data_users:/app/data
      - ./shared_data:/app/shared_data
    environment:
      - PORT=5050
    restart: unless-stopped

  filesvc:
    build: .
    command: [ "hypercorn", "src.file:app", "--bind", "0.0.0.0:5051" ]
    ports:
      - "5051:5051"
    volumes:
      - ./data_files:/app/data
      - ./shared_data:/app/shared_data
    environment:
      - PORT=5051
    depends_on:
      - usersvc
    restart: unless-stopped
